{% set version = "0.6.10" %}

package:
  name: cargo-llvm-cov
  version: {{ version }}

source:
  url: https://github.com/taiki-e/cargo-llvm-cov/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b8250ee10a3902b20c5c93b3ddd37e98a375048e9c7d500c5dafc950c3790415

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}  # [linux]
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  requires:
    - {{ compiler('rust') }}
  commands:
    - cargo llvm-cov --help  # [build_platform == target_platform]

about:
  home: https://github.com/taiki-e/cargo-llvm-cov
  license: Apache-2.0
  license_family: Apache
  summary: Cargo subcommand to easily use LLVM source-based code coverage (-C instrument-coverage).
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - borchero
